server.port: 8081

spring:
  application.name: account-s
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:32001/account
    username: nihilus
    password: nihilus
  rabbitmq:
    host: localhost
    port: 32101

management.endpoints.web.exposure.include: '*'
