version: "3"

services:
  account-service-db:
    image: postgres
    ports:
      - 6001:5432
    environment:
      - POSTGRES_DB=account
      - POSTGRES_USER=nihilus
      - POSTGRES_PASSWORD=nihilus
  inventory-service-db:
    image: postgres
    ports:
      - 6002:5432
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=nihilus
      - POSTGRES_PASSWORD=nihilus
  order-service-db:
    image: postgres
    ports:
      - 6003:5432
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=nihilus
      - POSTGRES_PASSWORD=nihilus
  payment-service-db:
    image: postgres
    ports:
      - 6004:5432
    environment:
      - POSTGRES_DB=payment
      - POSTGRES_USER=nihilus
      - POSTGRES_PASSWORD=nihilus
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
