apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  namespace: microshop
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: account-app
        args: [ "--spring.profiles.active=prod" ]