apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.3.0
    chart: rabbitmq
    helm:
      values: |
        auth:
          username: guest
          password: nihilus
        persistence:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: microshop
  syncPolicy:
    automated:
      prune: true