version: '3'

services:
  discovery-server:
    image: ahmsay/online-shopping-application:discovery-server
    ports:
      - 8761:8761
  config-server:
    image: ahmsay/online-shopping-application:config-server
    ports:
      - 8888:8888
    command: --spring.profiles.active=dockerCompose
  account-service:
    image: ahmsay/online-shopping-application:account-service
    ports:
      - 8081:8081
    command: --spring.profiles.active=dockerCompose
    depends_on:
      - dbpostgresql
  inventory-service:
    image: ahmsay/online-shopping-application:inventory-service
    ports:
      - 8082:8082
    command: --spring.profiles.active=dockerCompose
  order-service:
    image: ahmsay/online-shopping-application:order-service
    ports:
      - 8083:8083
    command: --spring.profiles.active=dockerCompose
  payment-service:
    image: ahmsay/online-shopping-application:payment-service
    ports:
      - 8084:8084
    command: --spring.profiles.active=dockerCompose
  dbpostgresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgre
      - POSTGRES_DB=mydb
