version: "3"

services:
  discovery-server:
    image: ahmsay/microshop-discovery-server:1.0
    ports:
      - 8761:8761
  config-server:
    image: ahmsay/microshop-config-server:1.0
    ports:
      - 8888:8888
    command: --spring.profiles.active=dockerCompose
  account-service:
    image: ahmsay/microshop-account-service:1.0
    ports:
      - 8081:8081
    command: --spring.profiles.active=dockerCompose
    depends_on:
      - account-service-db
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
  inventory-service:
    image: ahmsay/microshop-inventory-service:1.0
    ports:
      - 8082:8082
    command: --spring.profiles.active=dockerCompose
    depends_on:
      - inventory-service-db
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
  order-service:
    image: ahmsay/microshop-order-service:1.0
    ports:
      - 8083:8083
    command: --spring.profiles.active=dockerCompose
    depends_on:
      - order-service-db
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
  payment-service:
    image: ahmsay/microshop-payment-service:1.0
    ports:
      - 8084:8084
    command: --spring.profiles.active=dockerCompose
    depends_on:
      - payment-service-db
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
  account-service-db:
    image: postgres
    environment:
      - POSTGRES_DB=account
      - POSTGRES_USER=nihilus
      - POSTGRES_PASSWORD=nihilus
  inventory-service-db:
    image: postgres
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=nihilus
      - POSTGRES_PASSWORD=nihilus
  order-service-db:
    image: postgres
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=nihilus
      - POSTGRES_PASSWORD=nihilus
  payment-service-db:
    image: postgres
    environment:
      - POSTGRES_DB=payment
      - POSTGRES_USER=nihilus
      - POSTGRES_PASSWORD=nihilus
  rabbitmq:
    image: rabbitmq:management
