version: '3'

services:
  discovery-server:
    image: discovery-server-img
    build: ./discovery-server
    ports:
      - 8761:8761
  config-server:
    image: config-server-img
    build: ./config-server
    ports:
      - 8888:8888
  account-service:
    image: account-service-img
    build: ./account-service
    ports:
      - 8081:8081
  inventory-service:
    image: inventory-service-img
    build: ./inventory-service
    ports:
      - 8082:8082
  order-service:
    image: order-service-img
    build: ./order-service
    ports:
      - 8083:8083
  payment-service:
    image: payment-service-img
    build: ./payment-service
    ports:
      - 8084:8084