apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: microshop
spec:
  template:
    spec:
      containers:
      - name: payment-app
        args: [ "--spring.profiles.active=prod" ]