server.port: 8083

spring:
  application.name: order-s
  jpa:
    hibernate.ddl-auto: create
    properties.hibernate.globally_quoted_identifiers: true
  datasource:
    url: jdbc:postgresql://localhost:32003/order
    username: nihilus
    password: nihilus
  rabbitmq:
    host: localhost
    port: 32101

management.endpoints.web.exposure.include: '*'

exchanges:
  payment: payment.topic
queues:
  order: order.queue
routing-keys:
  payment:
    saved: payment.saved
