apiVersion: v1
kind: Pod
metadata:
  name: account-db
  namespace: microshop
  labels:
    db: account
spec:
  containers:
    - name: postgres
      image: postgres:15.0
      env:
        - name: POSTGRES_DB
          value: account
        - name: POSTGRES_USER
          value: nihilus
        - name: POSTGRES_PASSWORD
          value: nihilus
      ports:
        - containerPort: 5432
