server.port: 8084

spring:
  application.name: payment-service
  cloud.config.uri: http://config-server/

eureka.instance.lease-renewal-interval-in-seconds: 5

logging.level.org.springframework.retry: trace