server.port: 8084

spring:
  application.name: payment-s
  datasource:
    url: jdbc:postgresql://localhost:6004/payment
    username: nihilus
    password: nihilus
  jpa.hibernate.ddl-auto: create

management.endpoints.web.exposure.include: '*'

exchanges:
  payment: payment.topic
routing-keys:
  payment:
    saved: payment.saved
