apiVersion: v1
kind: Pod
metadata:
  name: inventory-db
  namespace: microshop
  labels:
    db: inventory
spec:
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_USER
          value: nihilus
        - name: POSTGRES_PASSWORD
          value: nihilus
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: init-db
          mountPath: "/docker-entrypoint-initdb.d"
          readOnly: true
  volumes:
    - name: init-db
      configMap:
        name: inventory-init-db
        items:
          - key: "init_db.sql"
            path: "init_db.sql"