apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  namespace: solidvessel
  labels:
    rabbit: rabbit
spec:
  containers:
    - name: rabbitmq
      image: rabbitmq:3.11.1-management
      ports:
        - containerPort: 5672
        - containerPort: 15672