apiVersion: v1
kind: Service
metadata:
  name: order-db-postgresql
  namespace: solidvessel
spec:
  type: NodePort
  selector:
    db: order
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32003