apiVersion: v1
kind: Pod
metadata:
  name: auth-db
  namespace: solidvessel
  labels:
    db: auth
spec:
  containers:
    - name: postgres
      image: postgres:15.0
      env:
        - name: POSTGRES_DB
          value: auth
        - name: POSTGRES_USER
          value: nihilus
        - name: POSTGRES_PASSWORD
          value: nihilus
      ports:
        - containerPort: 5432
