apiVersion: v1
kind: Service
metadata:
  name: auth-db-postgresql
  namespace: solidvessel
spec:
  type: NodePort
  selector:
    db: auth
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 31999