server.port: 8083

spring:
  application.name: order-s
  datasource:
    url: jdbc:postgresql://localhost:6003/order
    username: nihilus
    password: nihilus
  jpa:
    hibernate.ddl-auto: create
    properties.hibernate.globally_quoted_identifiers: true

management.endpoints.web.exposure.include: '*'

payment.exchange: payment_exchange
order.queue: order_queue
payment.saved.key: payment.saved
