server.port: 8084

spring:
  application.name: payment-s
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:32004/payment
    username: nihilus
    password: nihilus
  rabbitmq:
    host: localhost
    port: 32101

management.endpoints.web.exposure.include: '*'

exchanges:
  payment: payment.topic
routing-keys:
  payment:
    saved: payment.saved
