apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: solidvessel
spec:
  template:
    spec:
      containers:
      - name: auth-app
        args: [ "--spring.profiles.active=prod" ]