apiVersion: v1
kind: Pod
metadata:
  name: payment-db
  namespace: solidvessel
  labels:
    db: payment
spec:
  containers:
    - name: postgres
      image: postgres:15.3
      env:
        - name: POSTGRES_DB
          value: payment
        - name: POSTGRES_USER
          value: nihilus
        - name: POSTGRES_PASSWORD
          value: nihilus
      ports:
        - containerPort: 5432
