version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
    - wget https://github.com/adoptium/temurin20-binaries/releases/download/jdk-20.0.1%2B9/OpenJDK20U-jdk_x64_linux_hotspot_20.0.1_9.tar.gz
    - tar -xvf OpenJDK20U-jdk_x64_linux_hotspot_20.*.tar.gz
    - sudo mv jdk-20.0.1+9 /opt/
    - export JAVA_HOME=/opt/jdk-20.0.1+9
    - export PATH=$PATH:$JAVA_HOME/bin
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
    - gradle jib --parallel
