version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
    - mvn clean install -f ./shared/pom.xml
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
    - mvn clean compile jib:build -f ./auth/pom.xml
    - mvn clean compile jib:build -f ./account/pom.xml
    - mvn clean compile jib:build -f ./inventory/pom.xml
    - mvn clean compile jib:build -f ./order/pom.xml
    - mvn clean compile jib:build -f ./payment/pom.xml
