apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: solidvessel
  labels:
    redis: redis
spec:
  containers:
    - name: redis
      image: redis:7.0.5-alpine3.16
      ports:
        - containerPort: 6379